/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminFleetRouteImport } from './routes/admin.fleet'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as BusBusIdRouteImport } from './routes/bus.$busId'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as RoutesRouteIdRouteImport } from './routes/routes.$routeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const BusBusIdRoute = BusBusIdRouteImport.update({
  id: '/bus/$busId',
  path: '/bus/$busId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/driver': typeof DriverRoute
  '/notifications': typeof NotificationsRoute
  '/report': typeof ReportRoute
  '/safety': typeof SafetyRoute
  '/track': typeof TrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/reports': typeof AdminReportsRoute
  '/bus/$busId': typeof BusBusIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/admin/': typeof AdminIndexRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/driver': typeof DriverRoute
  '/notifications': typeof NotificationsRoute
  '/report': typeof ReportRoute
  '/safety': typeof SafetyRoute
  '/track': typeof TrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/reports': typeof AdminReportsRoute
  '/bus/$busId': typeof BusBusIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/admin': typeof AdminIndexRoute
  '/routes': typeof RoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/driver': typeof DriverRoute
  '/notifications': typeof NotificationsRoute
  '/report': typeof ReportRoute
  '/safety': typeof SafetyRoute
  '/track': typeof TrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/reports': typeof AdminReportsRoute
  '/bus/$busId': typeof BusBusIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/admin/': typeof AdminIndexRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/book'
    | '/bookings'
    | '/driver'
    | '/notifications'
    | '/report'
    | '/safety'
    | '/track'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/fleet'
    | '/admin/reports'
    | '/bus/$busId'
    | '/routes/$routeId'
    | '/admin/'
    | '/routes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/bookings'
    | '/driver'
    | '/notifications'
    | '/report'
    | '/safety'
    | '/track'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/fleet'
    | '/admin/reports'
    | '/bus/$busId'
    | '/routes/$routeId'
    | '/admin'
    | '/routes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/book'
    | '/bookings'
    | '/driver'
    | '/notifications'
    | '/report'
    | '/safety'
    | '/track'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/fleet'
    | '/admin/reports'
    | '/bus/$busId'
    | '/routes/$routeId'
    | '/admin/'
    | '/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  BookingsRoute: typeof BookingsRoute
  DriverRoute: typeof DriverRoute
  NotificationsRoute: typeof NotificationsRoute
  ReportRoute: typeof ReportRoute
  SafetyRoute: typeof SafetyRoute
  TrackRoute: typeof TrackRoute
  BusBusIdRoute: typeof BusBusIdRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bus/$busId': {
      id: '/bus/$busId'
      path: '/bus/$busId'
      fullPath: '/bus/$busId'
      preLoaderRoute: typeof BusBusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  BookingsRoute: BookingsRoute,
  DriverRoute: DriverRoute,
  NotificationsRoute: NotificationsRoute,
  ReportRoute: ReportRoute,
  SafetyRoute: SafetyRoute,
  TrackRoute: TrackRoute,
  BusBusIdRoute: BusBusIdRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
